language: csharp
sudo: required
dist: trusty
addons:
  sonarqube: true
sonarqube:
  branches:
    - develop
    - master
env:
  - CLI_VERSION=latest
os:  
  - linux
services:
  - mongodb
# Nur master und develop-Branches verwenden
branches:
  only:
    - master
    - develop
before_install:
  - chmod +x ./analyseSonarQube.sh
install:  
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
script:
  - ./build.sh
#  - ./analyseSonarQube.sh
cache:
  directories:
    - '$HOME/.sonar/cache'