version: 1.0.{build}
branches:
  only:
  - master
  - develop
services:
  - mongodb
build_script:
- ps: . ./build.ps1
- ps: choco install "msbuild-sonarqube-runner" -y
- ps: MSBuild.SonarQube.Runner.exe begin /k:"test:school" /n:"school" /v:"1.0.*" /d:sonar.host.url=https://sonarqube.com /d:sonar.login=[SonarToken]
platform: Any CPU
configuration: Release
test: off
artifacts:
  - path: artifacts/output.zip
max_jobs: 1