version: 1.0.{build}
branches:
  only:
  - master
  - develop
services:
  - mongodb
build_script:
- ps: . ./build.ps1
platform: Any CPU
configuration: Release
artifacts:
  - path: artifacts/output.zip
max_jobs: 1