version: 1.0.{build}
branches:
  only:
  - master
  - develop
services:
  - mongodb
#environment:
#  SonarToken:
#    secure: CH7kidekgG5BsX1Q2IyprUMuhim0d5s/KZMHGe78hgvYChkf1aKx0Zh1mZKbysKG
build_script:
- ps: . ./build.ps1
- ps: choco install "sonarcube-scanner" -y
#- ps: sonar-scanner -Dsonar.projectKey="test:school" -Dsonar.sources="src" -Dsonar.version="1.0.*" -Dsonar.host.url="https://sonarqube.com -Dsonar.login=$SonarToken
platform: Any CPU
configuration: Release
test: off
artifacts:
  - path: artifacts/output.zip
max_jobs: 1